// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdZU1wn_vSw47jzDj7PmlG1KvJ4eH1RKg',
    appId: '1:577439199236:web:30ab977be4bd2732394551',
    messagingSenderId: '577439199236',
    projectId: 'cicd-demo-9ee03',
    authDomain: 'cicd-demo-9ee03.firebaseapp.com',
    storageBucket: 'cicd-demo-9ee03.firebasestorage.app',
    measurementId: 'G-MKRLBKK3F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYgIhnLHDRf_ntWhaVgcDFfzKgdrcnxA',
    appId: '1:577439199236:android:3a45f689b269d76b394551',
    messagingSenderId: '577439199236',
    projectId: 'cicd-demo-9ee03',
    storageBucket: 'cicd-demo-9ee03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr64oqnY5ZcxR33N_zYmpL5jXHuo-KOAM',
    appId: '1:577439199236:ios:0257a8f7db56a728394551',
    messagingSenderId: '577439199236',
    projectId: 'cicd-demo-9ee03',
    storageBucket: 'cicd-demo-9ee03.firebasestorage.app',
    iosBundleId: 'com.example.cicdDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr64oqnY5ZcxR33N_zYmpL5jXHuo-KOAM',
    appId: '1:577439199236:ios:0257a8f7db56a728394551',
    messagingSenderId: '577439199236',
    projectId: 'cicd-demo-9ee03',
    storageBucket: 'cicd-demo-9ee03.firebasestorage.app',
    iosBundleId: 'com.example.cicdDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdZU1wn_vSw47jzDj7PmlG1KvJ4eH1RKg',
    appId: '1:577439199236:web:854b7395333bdf81394551',
    messagingSenderId: '577439199236',
    projectId: 'cicd-demo-9ee03',
    authDomain: 'cicd-demo-9ee03.firebaseapp.com',
    storageBucket: 'cicd-demo-9ee03.firebasestorage.app',
    measurementId: 'G-W858SYMM8N',
  );
}
